import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { FiFileText, FiAlertTriangle, FiUserCheck, FiZap, FiArrowLeft } from 'react-icons/fi';
import { SidebarFooter } from '../../components/Footer.jsx';

export function TermsPage() {
  return (
    <div className="flex min-h-screen bg-gradient-to-br from-[#EAE6F5] via-[#F4F0FB] to-[#FCEEF9] font-sans text-gray-900">
      
      {/* Sidebar */}
      <aside className="w-64 bg-[#E0D0F5]/40 backdrop-blur-md border-r border-white/50 flex flex-col justify-between hidden lg:flex sticky top-0 h-screen shadow-lg">
        <div className="p-8">
          <h1 className="text-2xl font-bold font-heading tracking-tight leading-tight text-gray-900 text-center uppercase">
            OutreachAI <br /> Sales <br /> Copilot
          </h1>
        </div>

        <nav className="flex flex-col gap-10 items-center font-light font-subheading text-gray-700 text-base">
          <Link to="/" className="nav-link-underline pb-1 transition-colors">Workspace</Link>
          <Link to="/history" className="nav-link-underline pb-1 transition-colors">History</Link>
          <Link to="/guide" className="nav-link-underline pb-1 transition-colors">How to Use</Link>
          <Link to="/settings" className="nav-link-underline pb-1 transition-colors">Settings</Link>
        </nav>

        <SidebarFooter />
      </aside>

      <main className="flex-1 p-8 md:p-16 h-screen overflow-y-auto custom-scrollbar">
        <div className="max-w-3xl mx-auto">
          <header className="mb-12">
            <Link to="/settings" className="inline-flex items-center gap-2 text-sm font-semibold text-[#A78BFA] hover:underline mb-8">
              <FiArrowLeft /> Back to Settings
            </Link>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <h2 className="text-4xl font-bold font-heading tracking-tight">Terms of Service</h2>
              <p className="text-gray-500 mt-4 font-light">Last Updated: May 2026</p>
            </motion.div>
          </header>

          <article className="glass-panel rounded-3xl p-8 md:p-12 border border-white/60 space-y-12">
            
            <section className="space-y-4">
              <div className="flex items-center gap-3 text-xl font-bold font-heading text-gray-900">
                <FiUserCheck className="text-[#A78BFA]" />
                <h3>1. Acceptance of Terms</h3>
              </div>
              <p className="text-gray-600 font-light leading-relaxed">
                By accessing or using OutreachAI Sales Copilot, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform. OutreachAI is a tool designed to assist professional sales teams in crafting personalized communications.
              </p>
            </section>

            <section className="space-y-4">
              <div className="flex items-center gap-3 text-xl font-bold font-heading text-gray-900">
                <FiZap className="text-[#A78BFA]" />
                <h3>2. AI-Generated Content</h3>
              </div>
              <p className="text-gray-600 font-light leading-relaxed">
                OutreachAI uses Artificial Intelligence (AI) to generate outreach suggestions. 
                <br /><br />
                - <strong>User Responsibility:</strong> You are solely responsible for reviewing, editing, and verifying the accuracy of any content generated by the AI before sending it to prospects.
                <br />
                - <strong>No Guarantee:</strong> We do not guarantee the accuracy, completeness, or effectiveness of AI-generated messages. AI can occasionally produce "hallucinations" or factually incorrect information.
              </p>
            </section>

            <section className="space-y-4">
              <div className="flex items-center gap-3 text-xl font-bold font-heading text-gray-900">
                <FiAlertTriangle className="text-[#A78BFA]" />
                <h3>3. Professional Conduct & Spam</h3>
              </div>
              <p className="text-gray-600 font-light leading-relaxed">
                OutreachAI is built for <strong>high-quality, personalized outreach</strong>. 
                <br /><br />
                - You agree not to use the platform for high-volume spam, illegal solicitation, or any activity that violates anti-spam laws (such as CAN-SPAM or GDPR).
                <br />
                - We reserve the right to suspend accounts that are found to be abusing the platform for malicious purposes.
              </p>
            </section>

            <section className="space-y-4">
              <div className="flex items-center gap-3 text-xl font-bold font-heading text-gray-900">
                <FiFileText className="text-[#A78BFA]" />
                <h3>4. Limitation of Liability</h3>
              </div>
              <p className="text-gray-600 font-light leading-relaxed">
                OutreachAI and its creators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of the platform, including but not limited to loss of business, data, or reputation caused by AI-generated communications.
              </p>
            </section>

            <div className="pt-8 border-t border-white/40">
              <p className="text-sm text-gray-400 font-light italic text-center">
                These terms are subject to change. Continued use of the platform constitutes acceptance of updated terms.
              </p>
            </div>
          </article>
        </div>
      </main>
    </div>
  );
}
